/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlthuocstore;

import static com.mysql.cj.protocol.x.XProtocolDecoder.instance;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Phuc
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private static Login instance;
    
    public Login() {
        initComponents();
        
//        jLogin.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                String username = jLoginUserName.getText();
//                String password = new String(jLoginUserPassword.getPassword());
//
//                if (username.equals("admin") && password.equals("123456")) {
//                    // Mở JFrame của Admin và hiển thị jp1
//                    Admin adminFrame = new Admin();
//                    adminFrame.setVisible(true);
//                    adminFrame.jp1.setVisible(true); // Hiển thị panel jp1 mặc định
//                    adminFrame.jp2.setVisible(false); // Ẩn panel jp2 ban đầu
//                    dispose(); // Đóng JFrame Login
//                } else {
//                    // Hiển thị thông báo lỗi
//                    JOptionPane.showMessageDialog(null, "Tên đăng nhập hoặc mật khẩu không đúng", "Lỗi đăng nhập", JOptionPane.ERROR_MESSAGE);
//                }
//            }
//        });
    }

    public static Login getInstance() {
        if (instance == null) {
            instance = new Login();
        }
        return instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLogin = new javax.swing.JButton();
        jLoginUserPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLoginUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/herbal (1).png"))); // NOI18N
        jLabel2.setText("Medick Flare");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, -1));

        jLogin.setBackground(new java.awt.Color(51, 204, 255));
        jLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLogin.setText("Đăng nhập");
        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 170, 60));

        jLoginUserPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jLoginUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 270, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Mật khẩu");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLoginUserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jLoginUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 270, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Tên đăng nhập");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Sign In");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
        String username = jLoginUserName.getText();
        String password = new String(jLoginUserPassword.getPassword());

        // Kiểm tra dữ liệu đầu vào
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Kiểm tra điều kiện đặc biệt
        if ("admin".equalsIgnoreCase(username) && "admin".equals(password)) {
            Admin adminFrame = new Admin();
            adminFrame.setVisible(true);
            adminFrame.jp1.setVisible(true); // Hiển thị panel jp1 mặc định
            adminFrame.jp2.setVisible(false); // Ẩn panel jp2 ban đầu
            dispose(); // Đóng JFrame Login
            return;
        }
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/qlthuocstore";
            String user = "root";
            String pass = ""; // Mật khẩu của bạn

            Connection con = DriverManager.getConnection(url, user, pass);
            Statement st = con.createStatement();

            // Xác thực người dùng
            String query = "SELECT PhanQuyen FROM TaiKhoanNV WHERE TenDangNhap='" + username + "' AND MatKhau='" + password + "'";
            System.out.println("Executing query: " + query); // Debug: in ra câu lệnh SQL
            ResultSet rs = st.executeQuery(query);

            if (rs.next()) {
                String phanQuyen = rs.getString("PhanQuyen");
                System.out.println("PhanQuyen found: " + phanQuyen); // Debug: in ra phân quyền

                // Điều hướng đến JFrame tương ứng dựa trên phân quyền có dấu
                if ("Admin".equalsIgnoreCase(phanQuyen)) {
                    Admin adminFrame = new Admin();
                    adminFrame.setVisible(true);
                    adminFrame.jp1.setVisible(true); // Hiển thị panel jp1 mặc định
                    adminFrame.jp2.setVisible(false); // Ẩn panel jp2 ban đầu
                } else if ("Quản lí".equalsIgnoreCase(phanQuyen)) {
                    QuanLy quanLyFrame = new QuanLy(); // Tạo một JFrame QuanLy
                    quanLyFrame.setVisible(true);
                    quanLyFrame.jp1.setVisible(true); // Hiển thị panel jp1 mặc định
                    quanLyFrame.jp2.setVisible(false); // Ẩn panel jp2 ban đầu
                    quanLyFrame.jp3.setVisible(false); // Ẩn panel jp3 ban đầu
                    quanLyFrame.jp4.setVisible(false); // Ẩn panel jp4 ban đầu
                    quanLyFrame.jp5.setVisible(false); // Ẩn panel jp5 ban đầu
                    quanLyFrame.jp6.setVisible(false); // Ẩn panel jp6 ban đầu
                } else if ("Nhân viên".equalsIgnoreCase(phanQuyen)) {
                    NhanVien nhanVienFrame = new NhanVien(); // Tạo một JFrame NhanVien
                    nhanVienFrame.setVisible(true);
                    nhanVienFrame.jp1.setVisible(true); // Hiển thị panel jp1 mặc định
                    nhanVienFrame.jp2.setVisible(false); // Ẩn panel jp2 ban đầu
                    nhanVienFrame.jp3.setVisible(false); // Ẩn panel jp3 ban đầu
                    nhanVienFrame.jp4.setVisible(false); // Ẩn panel jp4 ban đầu
                    nhanVienFrame.jp5.setVisible(false); // Ẩn panel jp5 ban đầu
                    nhanVienFrame.jp6.setVisible(false); // Ẩn panel jp6 ban đầu
                } else {
                    JOptionPane.showMessageDialog(this, "Phân quyền không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                dispose(); // Đóng JFrame Login
            } else {
                // Hiển thị thông báo lỗi
                JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không đúng.", "Lỗi đăng nhập", JOptionPane.ERROR_MESSAGE);
            }

            // Đóng kết nối
            con.close();

        } catch (Exception e) {
            // Xử lý lỗi
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jLogin;
    private javax.swing.JTextField jLoginUserName;
    private javax.swing.JPasswordField jLoginUserPassword;
    // End of variables declaration//GEN-END:variables
}
